name: todo_app
description: An example todos app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.2
  get_it: ^7.2.0
  injectable: ^2.1.1
  intl: ^0.17.0
  json_annotation: ^4.6.0
  meta: ^1.7.0
  rxdart: ^0.27.7
  shared_preferences: ^2.1.0
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  injectable_generator:  
  json_serializable: ^6.3.1
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  test: ^1.21.4

flutter:
  uses-material-design: true
  generate: true
